### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by wuzhongyi1105** [bashrc2/epicyon#1]
I carefully followed the steps of the official documentation and got the following error:

```
Traceback (most recent call last):
Apr  2 02:10:36 bb8d8d python3[685777]:   File "/opt/epicyon/epicyon.py", line 49, in <module>
Apr  2 02:10:36 bb8d8d python3[685777]:     from newswire import get_rss
Apr  2 02:10:36 bb8d8d python3[685777]:   File "/opt/epicyon/newswire.py", line 308
Apr  2 02:10:36 bb8d8d python3[685777]:     <<<<<<< HEAD
Apr  2 02:10:36 bb8d8d python3[685777]:     ^
Apr  2 02:10:36 bb8d8d python3[685777]: SyntaxError: invalid syntax
```
I am using Ubuntu 20.04, My python version:
```
root@bb8d8d:/opt/epicyon# python3
Python 3.8.10 (default, Nov 26 2021, 20:14:08)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by bashrc2** [comment]
It's because this is just a mirror from gitlab and the github version is updated automatically. It should be fixed now.

**Comment by wuzhongyi1105** [comment]
thanks👍
